version: '3'
services:
  client:
    build: 
      context: ./client
      dockerfile: Dockerfile.react
    ports:
      - "8001:8001"

  api:
    build: 
      context: ./api
      dockerfile: Dockerfile.python
    ports:
      - "8000:8000"
