version: '3'
services:
  client:
    build: 
      context: ./client
      dockerfile: Dockerfile.react
    ports:
      - "3001:3001"   #8001 of the host to 3000 if the container

  api:
    build: 
      context: ./api
      dockerfile: Dockerfile.python
    ports:
      - "8009:8009"
